title: "DAZ Consulting DS"
description: "Industrial EPC Advisory | Project Controls | Risk & Delivery Assurance"
author: Damian A. Stępień

baseurl: ""
url: "https://dazconsultingds.com/"

markdown: kramdown
permalink: /:categories/:title/

# render pages from _pages (because it starts with underscore)
include:
  - _pages

# navigation files (optional if you use custom nav in default.html, but ok to keep)
header_pages:
  - _pages/services.md
  - _pages/about.md
  - writeups/README.md
  - articles/README.md
  - certifications/README.md
  - progress/README.md
  - _pages/contact.md
